const products = [
  {
    price: 9,
    discount: 10,
    tag: JSON.stringify(["action", "adventure"]),
    flashSale: false,
    status: "Show",
    title: "Life of Pi",
    author: "Yann Martel",
    slug: "Life of pi",
    parent: "Action and Adventure",
    children: "Adventure",
    image: "https://i.ibb.co/WfnVcTs/1572292455-51rx-Ev-Llj-UL-2.png",
    originalPrice: 10,
    unit: "72",
    quantity: 100,
    type: "Adventure",
    description:
      "Action and adventure books constantly have you on the edge of your seat with excitement, as your fave main character repeatedly finds themselves in high stakes situations. The protagonist has an ultimate goal to achieve.",
    __v: 0,
  },
  {
    price: 14,
    discount: 0,
    tag: JSON.stringify(["action", "adventure"]),
    flashSale: false,
    status: "Show",
    title: "The musketeers",
    author: "Alexander dumas",
    slug: "The musketeers",
    parent: "Action and Adventure",
    children: "Adventure",
    image: "https://i.ibb.co/pzdRqT6/1572292481-41-Tx-Xq-To-CCL-1.png",
    originalPrice: 14,
    unit: "72",
    quantity: 100,
    type: "Adventure",
    description:
      "Action and adventure books constantly have you on the edge of your seat with excitement, as your fave main character repeatedly finds themselves in high stakes situations. The protagonist has an ultimate goal to achieve.",
    __v: 0,
  },
  {
    price: 12,
    discount: 20,
    tag: JSON.stringify(["action", "adventure"]),
    flashSale: false,
    status: "Show",
    title: "The call of wild",
    author: "Jack london",
    slug: "The call of wild",
    parent: "Action and Adventure",
    children: "Adventure",
    image: "https://i.ibb.co/6wt4tZ7/1572292481-41-Tx-Xq-To-CCL-1-1.png",
    originalPrice: 15,
    unit: "20",
    quantity: 10,
    type: "Adventure",
    description:
      "Action and adventure books constantly have you on the edge of your seat with excitement, as your fave main character repeatedly finds themselves in high stakes situations. The protagonist has an ultimate goal to achieve.",
    __v: 0,
  },
  {
    price: 12,
    discount: 0,
    tag: JSON.stringify(["classics"]),
    flashSale: false,
    status: "Show",
    title: "To kill a mockingbir",
    author: "Haprer lee",
    slug: "kill a mockingbird",
    parent: "Classics",
    children: "classics",
    image: "https://i.ibb.co/DWNGYhj/1572292481-41-Tx-Xq-To-CCL-1-2.png",
    originalPrice: 12,
    unit: "100g",
    quantity: 100,
    type: "Classics",
    description:
      "You may think of these books as the throwback readings you were assigned in English class. (Looking at you, Charles Dickens.) The classics have been around for decades, and were often groundbreaking stories at their publish time, but have continued to be impactful for generations, serving as the foundation for many popular works we.",
    __v: 0,
  },
  {
    price: 11,
    discount: 15,
    tag: JSON.stringify(["classics"]),
    flashSale: false,
    status: "Show",
    title: "Little women",
    author: "Lonisa",
    slug: "Little women",
    parent: "Classics",
    children: "classics",
    image: "https://i.ibb.co/1fb2nzx/1572292481-41-Tx-Xq-To-CCL-1-3.png",
    originalPrice: 13,
    unit: "100g",
    quantity: 100,
    type: "Classics",
    description:
      "You may think of these books as the throwback readings you were assigned in English class. (Looking at you, Charles Dickens.) The classics have been around for decades, and were often groundbreaking stories at their publish time, but have continued to be impactful for generations, serving as the foundation for many popular works we.",
    __v: 0,
  },
  {
    price: 12,
    discount: 0,
    tag: JSON.stringify(["classics"]),
    flashSale: false,
    status: "Show",
    title: "Beloved",
    author: "Toni morrison",
    slug: "Beloved",
    parent: "Classics",
    children: "classics",
    image: "https://i.ibb.co/s18R0gq/1572292709-41-Rdzbiqh7-L.png",
    originalPrice: 12,
    unit: "100g",
    quantity: 100,
    type: "Classics",
    description:
      "You may think of these books as the throwback readings you were assigned in English class. (Looking at you, Charles Dickens.) The classics have been around for decades, and were often groundbreaking stories at their publish time, but have continued to be impactful for generations, serving as the foundation for many popular works we.",
    __v: 0,
  },
  {
    price: 8,
    discount: 10,
    tag: JSON.stringify(["Comic Book", "Graphic Novel"]),
    flashSale: false,
    status: "Show",
    title: "DC Comics Watchmen",
    author: "Alan moore",
    slug: "DC Comics Watchmen",
    parent: "Comic Book",
    children: "Comic",
    image: "https://i.ibb.co/x8m65Fp/1572292709-41-Rdzbiqh7-L-1.png",
    originalPrice: 9,
    unit: "36pcs",
    quantity: 100,
    type: "Comic Book",
    description:
      "The stories in comic books and graphic novels are presented to the reader through engaging, sequential narrative art (illustrations and typography) that's either presented in a specific design or the traditional panel layout you find in comics. With both, you'll often find the dialogue presented in the tell-tale",
    __v: 0,
  },
  {
    price: 12,
    discount: 20,
    tag: JSON.stringify(["Comic Book", "Graphic Novel"]),
    flashSale: false,
    status: "Show",
    title: "The Walking Dead",
    author: "Alan moore",
    slug: "The Walking Dead",
    parent: "Comic Book",
    children: "Comic",
    image: "https://i.ibb.co/QD2rM6P/1572292709-41-Rdzbiqh7-L-2.png",
    originalPrice: 15,
    unit: "36pcs",
    quantity: 100,
    type: "Comic Book",
    description:
      "The stories in comic books and graphic novels are presented to the reader through engaging, sequential narrative art (illustrations and typography) that's either presented in a specific design or the traditional panel layout you find in comics. With both, you'll often find the dialogue presented in the tell-tale",
    __v: 0,
  },
  {
    price: 22,
    discount: 0,
    tag: JSON.stringify(["Comic Book", "Graphic Novel"]),
    flashSale: false,
    status: "Show",
    title: "HarperOne The Boy",
    author: "Chalie mackey",
    slug: "HarperOne The Boy",
    parent: "Comic Book",
    children: "Comic",
    image: "https://i.ibb.co/Rj8LZZx/1572292709-41-Rdzbiqh7-L-3.png",
    originalPrice: 22,
    unit: "36pcs",
    quantity: 100,
    type: "Comic Book",
    description:
      "The stories in comic books and graphic novels are presented to the reader through engaging, sequential narrative art (illustrations and typography) that's either presented in a specific design or the traditional panel layout you find in comics. With both, you'll often find the dialogue presented in the tell-tale",
    __v: 0,
  },
  {
    price: 7,
    discount: 11,
    tag: JSON.stringify(["Detective", " Mystery"]),
    flashSale: false,
    status: "Show",
    title: "Michael connelly",
    author: "Renee ballard",
    slug: "Michael connelly",
    parent: "Detective and Mystery",
    children: "Detective",
    image: "https://i.ibb.co/NNCMk0c/1572292709-41-Rdzbiqh7-L-4.png",
    originalPrice: 8,
    unit: "24pcs",
    quantity: 99,
    type: "Detective and Mystery",
    description:
      "Baby Products are products intended to be used on infants and children under the age of three. Baby products are specially formulated to be mild and non-irritating and use ingredients that are selected for these properties. Baby products include baby shampoos and baby lotions, oils, powders and creams.",
    __v: 0,
  },
  {
    price: 9,
    discount: 10,
    tag: JSON.stringify(["Detective", " Mystery"]),
    flashSale: false,
    status: "Show",
    title: "Adventures of Sherlock Holmes",
    author: "Arthur conan",
    slug: "Adventures of Sherlock Holmes",
    parent: "Detective and Mystery",
    children: "Detective",
    image: "https://i.ibb.co/nwB7cmc/1572292709-41-Rdzbiqh7-L-5.png",
    originalPrice: 10,
    unit: "24pcs",
    quantity: 100,
    type: "Detective and Mystery",
    description:
      "Baby Products are products intended to be used on infants and children under the age of three. Baby products are specially formulated to be mild and non-irritating and use ingredients that are selected for these properties. Baby products include baby shampoos and baby lotions, oils, powders and creams.",
    __v: 0,
  },
  {
    price: 13,
    discount: 0,
    tag: JSON.stringify(["Detective", " Mystery"]),
    flashSale: false,
    status: "Show",
    title: "And Then There Were None",
    author: "Renee ballard",
    slug: "And Then There Were None",
    parent: "Detective and Mystery",
    children: "Detective",
    image: "https://i.ibb.co/Nyf9SGM/1572293489-51-Mlx-Ng-Csy-L.png",
    originalPrice: 13,
    unit: "24pcs",
    quantity: 100,
    type: "Detective and Mystery",
    description:
      "Baby Products are products intended to be used on infants and children under the age of three. Baby products are specially formulated to be mild and non-irritating and use ingredients that are selected for these properties. Baby products include baby shampoos and baby lotions, oils, powders and creams.",
    __v: 0,
  },
  {
    price: 16,
    discount: 0,
    tag: JSON.stringify(["Fantasy"]),
    flashSale: false,
    status: "Show",
    title: "One World The Water Dancer",
    slug: "One World The Water Dancer",
    author: "Oprah's",
    parent: "Fantasy",
    children: "Fantasy",
    image: "https://i.ibb.co/h9R7YJc/1572293716-51-Itgi-Zw5d-L.png",
    originalPrice: 16,
    unit: "32pcs",
    quantity: 0,
    type: "Fantasy",
    description:
      "While usually set in a fictional imagined world—in opposition, Ta-Nehisi's Coates's The Water Dancer takes place in the very real world of American slavery—fantasy books include prominent elements of magic, mythology, or the supernatural..",
    __v: 0,
  },
  {
    price: 14,
    discount: 22,
    tag: JSON.stringify(["Fantasy"]),
    flashSale: false,
    status: "Show",
    title: "Circe",
    slug: "Circe",
    author: "Madeline miller",
    parent: "Fantasy",
    children: "Fantasy",
    image: "https://i.ibb.co/1q3ghhH/1572293746-51dzuw-Lmm-L.png",
    originalPrice: 17,
    unit: "32pcs",
    quantity: 0,
    type: "Fantasy",
    description:
      "While usually set in a fictional imagined world—in opposition, Ta-Nehisi's Coates's The Water Dancer takes place in the very real world of American slavery—fantasy books include prominent elements of magic, mythology, or the supernatural..",
    __v: 0,
  },
  {
    price: 14,
    discount: 0,
    tag: JSON.stringify(["Fantasy"]),
    flashSale: false,
    status: "Show",
    title: "Ninth House",
    slug: "One World The Water Dancer",
    author: "Oprah's",
    parent: "Fantasy",
    children: "Fantasy",
    image: "https://i.ibb.co/HN0RR4r/1572293766-41c-Ux-Ntr5-L.png",
    originalPrice: 14,
    unit: "32pcs",
    quantity: 0,
    type: "Fantasy",
    description:
      "Baby Products are products intended to be used on infants and children under the age of three. Baby products are specially formulated to be mild and non-irritating and use ingredients that are selected for these properties. Baby products include baby shampoos and baby lotions, oils, powders and creams.",
    __v: 0,
  },
  {
    price: 14,
    discount: 10,
    tag: JSON.stringify(["Historical Fiction"]),
    flashSale: false,
    status: "Show",
    title: "The help",
    slug: "the help",
    author: "Kathryn stockett",
    parent: "Historical Fiction",
    children: "Historical Fiction",
    image: "https://i.ibb.co/VmtvjZd/1572293965-51-D9-Lg-Mg-L.png",
    originalPrice: 15,
    unit: "200gm",
    quantity: 99,
    type: "Historical Fiction",
    description:
      "These books are based in a time period set in the past decades, often against the backdrop of significant (real) historical events. developed muscles and teeth to effectively chew. Babies typically move to consuming baby food once nursing or formula is not sufficient for the child's appetite. Babies do not need to have teeth to transition to eating solid foods.",
    __v: 0,
  },
  {
    price: 16,
    discount: 0,
    tag: JSON.stringify(["Historical Fiction"]),
    flashSale: false,
    status: "Show",
    title: "One Hundred Years of Solitude",
    slug: "One Hundred Years of Solitude",
    author: "Gabriel garcia",
    parent: "Historical Fiction",
    children: "Historical Fiction",
    image: "https://i.ibb.co/JtkhFt9/1572294012-51-Zr6-Pd32-ML.png",
    originalPrice: 16,
    unit: "200gm",
    quantity: 100,
    type: "Historical Fiction",
    description:
      "These books are based in a time period set in the past decades, often against the backdrop of significant (real) historical events. developed muscles and teeth to effectively chew. Babies typically move to consuming baby food once nursing or formula is not sufficient for the child's appetite. Babies do not need to have teeth to transition to eating solid foods.",
    __v: 0,
  },
  {
    price: 16,
    discount: 0,
    tag: JSON.stringify(["Historical Fiction"]),
    flashSale: false,
    status: "Show",
    title: "Vintage Memoirs of a Geisha",
    slug: "Vintage Memoirs of a Geisha",
    author: "Arthur golden",
    parent: "Historical Fiction",
    children: "Historical Fiction",
    image: "https://i.ibb.co/c1fY5Kz/1572294103-51-O9-Hq-W8-ZAL.png",
    originalPrice: 16,
    unit: "200gm",
    quantity: 100,
    type: "Historical Fiction",
    description:
      "These books are based in a time period set in the past decades, often against the backdrop of significant (real) historical events. developed muscles and teeth to effectively chew. Babies typically move to consuming baby food once nursing or formula is not sufficient for the child's appetite. Babies do not need to have teeth to transition to eating solid foods.",
    __v: 0,
  },
  {
    price: 16,
    discount: 20,
    tag: JSON.stringify(["Horror"]),
    flashSale: false,
    status: "Show",
    title: "Anchor Carrie",
    slug: "Anchor Carriey",
    author: "Stephen",
    parent: "Horror",
    children: "Horror",
    image: "https://i.ibb.co/ZmHvdCd/1572295234-51d-Rjo8-NJe-L.png",
    originalPrice: 20,
    unit: "400gm",
    quantity: 99,
    type: "Horror",
    description:
      "Meant to cause discomfort and fear for both the character and readers, horror writers often make use of supernatural and paranormal elements in morbid stories that are sometimes a little too realistic. The master of horror fiction? None other than Stephen King..",
    __v: 0,
  },
  {
    price: 17,
    discount: 0,
    tag: JSON.stringify(["Horror"]),
    flashSale: false,
    status: "Show",
    title: "The Haunting of Hill House",
    slug: "The Haunting of Hill House",
    author: "Shirley jackson",
    parent: "Horror",
    children: "Horror",
    image: "https://i.ibb.co/HdC2xWD/1572295266-51gy-Xcg1-P2-L.png",
    originalPrice: 17,
    unit: "400gm",
    quantity: 100,
    type: "Horror",
    description:
      "Meant to cause discomfort and fear for both the character and readers, horror writers often make use of supernatural and paranormal elements in morbid stories that are sometimes a little too realistic. The master of horror fiction? None other than Stephen King..",
    __v: 0,
  },
  {
    price: 18,
    discount: 10,
    tag: JSON.stringify(["Horror"]),
    flashSale: false,
    status: "Show",
    title: "Bird Box",
    slug: "Josh malerman",
    author: "Stephen",
    parent: "Horror",
    children: "Horror",
    image: "https://i.ibb.co/DfKjkM4/1572295284-41s-RIihn-Xz-L.png",
    originalPrice: 20,
    unit: "400gm",
    quantity: 99,
    type: "Horror",
    description:
      "Meant to cause discomfort and fear for both the character and readers, horror writers often make use of supernatural and paranormal elements in morbid stories that are sometimes a little too realistic. The master of horror fiction? None other than Stephen King..",
    __v: 0,
  },
  {
    price: 15,
    discount: 0,
    tag: JSON.stringify(["Literary Fiction"]),
    flashSale: false,
    status: "Show",
    title: "Where the Crawdads Sing",
    slug: "Where the Crawdads Sing",
    author: "Delia owens",
    parent: "Literary Fiction",
    children: "Literary Fiction",
    image: "https://i.ibb.co/SxcdPhT/1572295477-51j5p18m-JNL.png",
    originalPrice: 15,
    unit: "400gm",
    quantity: 100,
    type: "Literary Fiction",
    description:
      "Though it can be seen as a broad genre that encompasses many others, literary fiction refers to the perceived artistic writing style of the author. Their prose is meant to evoke deep thought through stories that offer personal or social commentary on a particular theme..",
    __v: 0,
  },
  {
    price: 15,
    discount: 0,
    tag: JSON.stringify(["Literary Fiction"]),
    flashSale: false,
    status: "Show",
    title: "Olive, Again",
    slug: "Olive, Again",
    author: "Ehzabeth",
    parent: "Literary Fiction",
    children: "Literary Fiction",
    image: "https://i.ibb.co/jZpbHKN/1572295477-51j5p18m-JNL-1.png",
    originalPrice: 15,
    unit: "400gm",
    quantity: 100,
    type: "Literary Fiction",
    description:
      "Though it can be seen as a broad genre that encompasses many others, literary fiction refers to the perceived artistic writing style of the author. Their prose is meant to evoke deep thought through stories that offer personal or social commentary on a particular theme..",
    __v: 0,
  },
  {
    price: 16,
    discount: 10,
    tag: JSON.stringify(["Literary Fiction"]),
    flashSale: false,
    status: "Show",
    title: "Harper The Dutch House",
    slug: "Harper The Dutch House",
    author: "Ann Patchett",
    parent: "Literary Fiction",
    children: "Literary Fiction",
    image: "https://i.ibb.co/9VDScJp/1572295539-51-Fi-W7t0-Gu-L.png",
    originalPrice: 18,
    unit: "400gm",
    quantity: 98,
    type: "Literary Fiction",
    description:
      "Though it can be seen as a broad genre that encompasses many others, literary fiction refers to the perceived artistic writing style of the author. Their prose is meant to evoke deep thought through stories that offer personal or social commentary on a particular theme..",
    __v: 0,
  },
  {
    price: 16,
    discount: 0,
    tag: JSON.stringify(["Romance"]),
    flashSale: false,
    status: "Show",
    title: "Brazen and the Beast",
    slug: "Brazen and the Beast",
    author: "Saran maclean",
    parent: "Romance",
    children: "Romance",
    image: "https://i.ibb.co/Hdx56p0/1572296390-51fi-EAOae4-L.png",
    originalPrice: 16,
    unit: "8pcs",
    quantity: 100,
    type: "Romance",
    description:
      "Oh romance, how could we ever resist you? The genre that makes your heart all warm and fuzzy focuses on the love story of the main protagonists. This world of fiction is extremely wide-reaching in and of itself, as it has a variety of sub-genres including: contemporary romance, historical, paranormal, and the steamier erotica. If you're in need of any suggestions, we've got ",
    __v: 0,
  },
  {
    price: 16,
    discount: 0,
    tag: JSON.stringify(["Romance"]),
    flashSale: false,
    status: "Show",
    title: "Berkley Royal Holiday",
    slug: "Berkley Royal Holiday",
    author: "Jasmine guillory",
    parent: "Romance",
    children: "Romance",
    image: "https://i.ibb.co/j4G9pzk/1572296414-51-Qdlk-QL.png",
    originalPrice: 16,
    unit: "8pcs",
    quantity: 100,
    type: "Romance",
    description:
      "Oh romance, how could we ever resist you? The genre that makes your heart all warm and fuzzy focuses on the love story of the main protagonists. This world of fiction is extremely wide-reaching in and of itself, as it has a variety of sub-genres including: contemporary romance, historical, paranormal, and the steamier erotica. If you're in need of any suggestions, we've got ",
    __v: 0,
  },
  {
    price: 16,
    discount: 0,
    tag: JSON.stringify(["Romance"]),
    flashSale: false,
    status: "Show",
    title: "The Savior",
    slug: "The Savior",
    author: "jr ward",
    parent: "Romance",
    children: "Romance",
    image: "https://i.ibb.co/kQYD2v5/1572296440-41-Rxnb-Daef-L.png",
    originalPrice: 16,
    unit: "8pcs",
    quantity: 100,
    type: "Romance",
    description:
      "Oh romance, how could we ever resist you? The genre that makes your heart all warm and fuzzy focuses on the love story of the main protagonists. This world of fiction is extremely wide-reaching in and of itself, as it has a variety of sub-genres including: contemporary romance, historical, paranormal, and the steamier erotica. If you're in need of any suggestions, we've got ",
    __v: 0,
  },
  {
    price: 11,
    discount: 0,
    tag: JSON.stringify(["Science Fiction"]),
    flashSale: false,
    status: "Show",
    title: "Nan A. Talese The Testaments",
    slug: "Nan A. Talese The Testaments",
    author: "Margaret atwood",
    parent: "Science Fiction",
    children: "Science Fiction",
    image: "https://i.ibb.co/jGS3xzs/1572296624-419-TWZk7lu-L.png",
    originalPrice: 11,
    unit: "70g",
    quantity: 100,
    type: "Science Fiction",
    description:
      "Though they're often thought of in the same vein as fantasy, what distinguishes science fiction stories is that they lean heavily on themes of technology and future science. You'll find apocalyptic and dystopian novels in the sci-fi genre as well",
    __v: 0,
  },
  {
    price: 11,
    discount: 0,
    tag: JSON.stringify(["Science Fiction"]),
    flashSale: false,
    status: "Show",
    title: "The Hunger Games Trilogy",
    slug: "The Hunger Games Trilogy",
    author: "Suzanne collins",
    parent: "Science Fiction",
    children: "Science Fiction",
    image: "https://i.ibb.co/Vxhb2f8/1572296661-41nphb8vb-PL.png",
    originalPrice: 11,
    unit: "70g",
    quantity: 100,
    type: "Science Fiction",
    description:
      "Though they're often thought of in the same vein as fantasy, what distinguishes science fiction stories is that they lean heavily on themes of technology and future science. You'll find apocalyptic and dystopian novels in the sci-fi genre as well",
    __v: 0,
  },
  {
    price: 11,
    discount: 0,
    tag: JSON.stringify(["Science Fiction"]),
    flashSale: false,
    status: "Show",
    title: "1984",
    slug: "1984",
    author: "George",
    parent: "Science Fiction",
    children: "Science Fiction",
    image: "https://i.ibb.co/f8pKqVb/1572296688-410-Zir-PKXKL.jpg",
    originalPrice: 11,
    unit: "70g",
    quantity: 99,
    type: "Science Fiction",
    description:
      "Though they're often thought of in the same vein as fantasy, what distinguishes science fiction stories is that they lean heavily on themes of technology and future science. You'll find apocalyptic and dystopian novels in the sci-fi genre as well",
    __v: 0,
  },
  {
    price: 12,
    discount: 0,
    tag: JSON.stringify(["Suspense", "Thrillers"]),
    flashSale: false,
    status: "Show",
    title: "Gone Girl",
    slug: "Gone Girl",
    author: "Impress cagly",
    parent: "Suspense",
    children: "suspence",
    image: "https://i.ibb.co/gDcq92b/1572297615-416-TH3igf-OL.png",
    originalPrice: 12,
    unit: "75g",
    quantity: 99,
    type: "Suspense and Thrillers",
    description:
      "While they often encompass the same elements as mystery books, the suspense and thriller genre sees the hero attempt to stop and defeat the villain to save their own life rather than uncover a specific crime.",
    __v: 0,
  },
  {
    price: 12,
    discount: 0,
    tag: JSON.stringify(["Suspense", "Thrillers"]),
    flashSale: false,
    status: "Show",
    title: "Doubleday The Guardians",
    slug: "Doubleday The Guardians",
    author: "John Grisham",
    parent: "Suspense",
    children: "suspence",
    image: "https://i.ibb.co/YfBLJsH/1572297648-51-U2h-IUQgq-L.png",
    originalPrice: 12,
    unit: "75g",
    quantity: 100,
    type: "Suspense and Thrillers",
    description:
      "While they often encompass the same elements as mystery books, the suspense and thriller genre sees the hero attempt to stop and defeat the villain to save their own life rather than uncover a specific crime.",
    __v: 0,
  },
  {
    price: 12,
    discount: 0,
    tag: JSON.stringify(["Suspense", "Thrillers"]),
    flashSale: false,
    status: "Show",
    title: "The 19th Christmas",
    slug: "The 19th Christmas",
    author: "Maxine paetro",
    parent: "Suspense",
    children: "suspence",
    image: "https://i.ibb.co/mSH7bhS/1572297634-51w-T1-Ny84s-L.png",
    originalPrice: 12,
    unit: "75g",
    quantity: 99,
    type: "Suspense and Thrillers",
    description:
      "While they often encompass the same elements as mystery books, the suspense and thriller genre sees the hero attempt to stop and defeat the villain to save their own life rather than uncover a specific crime.",
    __v: 0,
  },
];

module.exports = products;
